const { readFileSync, writeFileSync } = require('fs')

const root = './node_modules/obsidian'

writeFileSync(
  `${root}/index.js`,
  '// this file is generated by obisidian-firesync for testing purpose.'
)

const pkg = readFileSync(`${root}/package.json`)
const json = JSON.parse(pkg)
json.main = 'index.js'
writeFileSync(`${root}/package.json`, JSON.stringify(json))
